# Generated by Django 5.2.17 on 2026-09-11 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('token_number', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('technician_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lab_technician',
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('test_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('test_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal_range', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lab_test',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=10)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('receptionist_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'receptionist',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'specialization',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qualification', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
                ('license_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.department')),
                ('specialization', models.ForeignKey(db_column='specialization_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.specialization')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptoms', models.CharField(max_length=255)),
                ('diagnosis', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=500)),
                ('consultation_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('appointment', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.appointment')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.doctor')),
            ],
            options={
                'db_table': 'consultation',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.doctor'),
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('appointment', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.appointment')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.patient')),
            ],
            options={
                'db_table': 'lab_order',
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.laborder')),
                ('technician', models.ForeignKey(db_column='technician_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.labtechnician')),
                ('test', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.labtest')),
            ],
            options={
                'db_table': 'lab_order_item',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(max_length=255)),
                ('medical_notes', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('consultation', models.ForeignKey(db_column='consultation_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.consultation')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.patient')),
            ],
            options={
                'db_table': 'medical_record',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('appointment', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.appointment')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.patient')),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.patient'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('online', 'Online')], max_length=30)),
                ('payment_date', models.DateTimeField()),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bill', models.ForeignKey(db_column='bill_id', on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.bill')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('consultation', models.ForeignKey(db_column='consultation_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.consultation')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.patient')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionLabTest',
            fields=[
                ('prescription_lab_test_id', models.AutoField(primary_key=True, serialize=False)),
                ('instructions', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('prescription', models.ForeignKey(db_column='prescription_id', on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.prescription')),
                ('test', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.labtest')),
            ],
            options={
                'db_table': 'prescription_lab_test',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('instructions', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('medicine', models.ForeignKey(db_column='medicine_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.medicine')),
                ('prescription', models.ForeignKey(db_column='prescription_id', on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.prescription')),
            ],
            options={
                'db_table': 'prescription_medicine',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='receptionist',
            field=models.ForeignKey(db_column='receptionist_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.receptionist'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.department')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.AddField(
            model_name='receptionist',
            name='staff',
            field=models.OneToOneField(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.staff'),
        ),
        migrations.AddField(
            model_name='labtechnician',
            name='staff',
            field=models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.staff'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='staff',
            field=models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.staff'),
        ),
        migrations.AddField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.staff'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='receptionistapp.role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.user'),
        ),
    ]
