# Generated by Django 5.2.17 on 2026-10-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSetting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(default='ClinixOne Care Operations', max_length=150)),
                ('clinic_email', models.CharField(default='support@clinixone.com', max_length=100)),
                ('clinic_phone', models.CharField(default='+1 (800) 555-0199', max_length=20)),
                ('clinic_address', models.CharField(default='100 Medical Center Blvd, Suite 400', max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('appointment_slot_duration', models.IntegerField(default=15)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_email_alerts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clinic_setting',
            },
        ),
    ]
