# Generated by Django 5.2.17 on 2026-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clinicsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('pre_booking', 'Pre-Booking'), ('walk_in', 'Walk-In')], default='pre_booking', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('serving', 'Serving'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
